"""Add task_description to tasks

Revision ID: 314b34916af1
Revises: 
Create Date: 2024-11-26 19:22:35.698398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314b34916af1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('task_description')

    # ### end Alembic commands ###
