"""Add reoccurring field to Task model

Revision ID: 39347bdae104
Revises: af7f7538abfa
Create Date: 2024-11-27 03:49:14.283913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39347bdae104'
down_revision = 'af7f7538abfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reoccurring', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('reoccurring')

    # ### end Alembic commands ###
